import wx
from wx import *
app = App()
root = Frame(None,title="Indian Public School - Jayant",size=(1000,600))
def close(event):
    root.Close()
def cleardata(event):
    text.SetValue("")
def clearform(event):
    nametc.SetValue("")
    emailtc.SetValue("")
    classestc.SetValue("")
    addresstc.SetValue("")
    gendertc.SetValue("")
panel = Panel(root)
panel.SetBackgroundColour("#FFE0B2")
mainbox = BoxSizer(VERTICAL)
'''logoarea = BoxSizer(HORIZONTAL)
logo = StaticBitmap(panel,1,Bitmap("g:\python_logo\image\ips.png"))
logoarea.Add(logo,0,ALL|EXPAND)
brand = StaticText(panel,1,label="INDIAN PUBLIC SCHOOL", style=ALIGN_CENTER)
font = Font(32,FONTFAMILY_DECORATIVE,FONTSTYLE_NORMAL,FONTWEIGHT_BOLD)
brand.SetFont(font)
logoarea.Add(brand,0,ALL|EXPAND)'''
logoarea = StaticBitmap(panel,1,Bitmap("g:\python_logo\image\ipsname.png"))
mainbox.Add(logoarea,1,ALL|EXPAND,border=10)
'''nav = StaticText(panel,ID_ANY,label="Management", style=ALIGN_CENTER)
navfont = Font(16,FONTFAMILY_DECORATIVE,FONTSTYLE_NORMAL,FONTWEIGHT_BOLD)
nav.SetFont(navfont)
mainbox.Add(nav,0,ALL|EXPAND,border=10)'''
section = BoxSizer(HORIZONTAL)
#register = StaticBox(panel,label="Register")
f1 = BoxSizer(VERTICAL)
formgrp = GridSizer(10,1,5,5)
name = StaticText(panel,label="Name")
email = StaticText(panel,label="Email")
classes = StaticText(panel,label="Class")
gender = StaticText(panel,label="Gender")
address = StaticText(panel,label="Address")
nametc = TextCtrl(panel)
emailtc = TextCtrl(panel)
choice_list = [''+str(num) for num in range(1,13)]
classestc =  wx.Choice(panel, 1, choices=choice_list)
#classestc = TextCtrl(panel)
gendertc = TextCtrl(panel)
addresstc = TextCtrl(panel)
formgrp.AddMany([
    (name),(nametc,0,EXPAND|ALL),
    (email),(emailtc,0,EXPAND|ALL),
    (classes),(classestc,0,EXPAND|ALL),
    (gender),(gendertc,0,EXPAND|ALL),
    (address),(addresstc,0,EXPAND|ALL)
])
f1.Add(formgrp,5,ALL|EXPAND,border=10)
btngrp = GridSizer(1,2,10,10)
clear = Button(panel,label="Clear")
send = Button(panel,label="Send")
clear.SetBackgroundColour("#B0BEC5")
send.SetBackgroundColour("#EF9A9A")
clear.Bind(EVT_BUTTON,clearform,clear)
btngrp.AddMany([
    (clear,0,EXPAND|ALL),(send,0,EXPAND|ALL)
])
f1.Add(btngrp,1,ALL|EXPAND,border=10)
#register.Add(formgrp,0,ALL|EXPAND,border=10)
section.Add(f1,1,ALL|EXPAND,border=10)
f2 = BoxSizer(VERTICAL)
btngrp2 = GridSizer(1,4,10,10)
open = Button(panel,label="Open")
save = Button(panel,label="Save")
clear2 = Button(panel,label="Clear")
exit = Button(panel,label="Exit")
open.SetBackgroundColour("#4DB6AC")
save.SetBackgroundColour("#9575CD")
clear2.SetBackgroundColour("#AED581")
exit.SetBackgroundColour("#E57373")
exit.Bind(EVT_BUTTON,close,exit)
clear2.Bind(EVT_BUTTON,cleardata,clear2)
open.SetForegroundColour("white")
save.SetForegroundColour("white")
clear2.SetForegroundColour("white")
exit.SetForegroundColour("white")
clear.SetForegroundColour("white")
send.SetForegroundColour("white")
btngrp2.AddMany([
    (open,0,EXPAND|ALL),(save,0,EXPAND|ALL),
    (clear2,0,EXPAND|ALL),(exit,0,EXPAND|ALL)
])
f2.Add(btngrp2,1,EXPAND|ALL,border=10)
text = TextCtrl(panel,style=TE_MULTILINE)
f2.Add(text,5,EXPAND|ALL,border=10)
section.Add(f2,3,EXPAND|ALL,border=10)
mainbox.Add(section,4,ALL|EXPAND,border=10)
panel.SetSizer(mainbox)
root.Show()
app.MainLoop()